# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Quickstart'
  link: '/quickstart'
- label: API
  items:
    - label: 'User'
      link: '/api/user'
    - label: 'OCR'
      link: '/api/ocr'
    - label: 'Deck'
      link: '/api/deck'
    - label: 'Class'
      link: '/api/class'
- label: Community
  items:
    - label: 'Contributing'
      link: '/community/contributing'
    - label: 'Github'
      link: https://github.com/jadeocr/docs
